### ISSUE TITLE
Holaaaa

### ISSUE THREAD

**Issue by stringparser** [agarciamontoro/granasatServer#1]
Hey! De que va esto?

**Comment by agarciamontoro** [comment]
¡Hola!

Esto es un proyecto en el que llevamos liados desde octubre de 2013. Un grupo de estudiantes de la UGR (ingenieros, físicos, traductores...) nos presentamos para participar en REXUS/BEXUS, un programa del DLR y SNSB (agencias aeroespaciales alemana y sueca, respectivamente) en cooperación con la ESA (agencia aeroespacial europea).
Así muy rápido: hemos desarrollado un prototipo de sistema de orientación para pico-satélites y lo hemos testeado en un globo estratosférico que voló durante un par de horas a 27 kilómetros de altura en Kiruna, Suecia. La idea principal del proyecto era conjugar tres sistemas de orientación: un star tracker, un horizon sensor y un magnetómetro.

Este repositorio contiene el código ejecutado en la Raspberry que voló en el globo y que básicamente hacía tres cosas: tomar medidas (fotos, campo magnético y otras cosas menores), aplicar los algoritmos de orientación y mandar los resultados a la [estación de tierra](https://github.com/M42/granasatClient) -que programó @M42 -.

Tengo en mente actualizar el Readme con algunos resultados, terminar de documentar el código y poner algunas imágenes de las que captamos allí arriba (SPOILER: captamos una [bonita aurora boreal](https://www.youtube.com/watch?v=YUlWg6wuCxo) :) ).

**Comment by stringparser** [comment]
Oh my, ¡esto es la hostia! A finales de Febrero tendré más tiempo y voy a cotillearos sin vergüenza que lo sepas

**Comment by agarciamontoro** [comment]
Jajajaja, cuando quieras, para eso está. Hay gente que sigue trabajando en GranaSAT: la idea es diseñar un pico-satélite para la UGR -con el trabajo de alumnos- y ponerlo en órbita algún día. Esto ha sido un primer pasito :)

**Comment by stringparser** [comment]
¡Pues me siento satisfecho! Gracias tio, hablamos :)
